---
title: "functions-lesson"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


# Test data

```{r}
airtemps <-c(212, 30.3, 78, 32)
celsius1 <- (airtemps[[1]]-32)*5/9
celsius2 <- (airtemps[[2]]-32)*5/9
celsius3 <- (airtemps[[3]]-32)*5/9
celsius4 <- (airtemps[[4]]-32)*5/9

```

# Create your first function 

```{r}
fahr_to_celsius <- function(fahr) {
  celsius <- (fahr-32)*5/9
  return(celsius)
}
```

```{r}
celsius4<-fahr_to_celsius(airtemps[[1]]) # apply function to first element in object airtemps; double brackts [[]] returns a value. single bracket [] returns a vector.
celsius1 == celsius4 #check if it is correct

celsius<-fahr_to_celsius(airtemps) # apply function to all elements in object airtemps
celsius
```

# exercise
```{r}
celsius_to_fahr<-function(celsius) {
  fahr <- celsius*9/5 + 32
  return(fahr)
}

# apply function
fahr1<-celsius_to_fahr(celsius)
fahr1

fahr1 == airtemps

```
# Function with 2 arguments (x,y) and return one value

```{r}
mysum<-fucntion(x,y){
  return(x+y)
}
```

# Function that returns multiple values as a list

```{r}
convert_temps <- function(fahr) {
  celsius <- fahr_to_celsius(fahr)
  kelvin <- celsius + 273.15
  return(list(fahr=fahr, celsius=celsius, kelvin=kelvin))
}

convert_temps(32)

temps_df <- data.frame(convert_temps(seq(-100,100,10)))
temps_df

```

# Creating a function for a theme in ggplot

```{r}
custom_theme <- function(base_size = 9) {
    ggplot2::theme(
      axis.ticks       = ggplot2::element_blank(),
      text             = ggplot2::element_text(family = 'Helvetica', color = 'gray30', size = base_size),
      plot.title       = ggplot2::element_text(size = ggplot2::rel(1.25), hjust = 0.5, face = 'bold'),
      panel.background = ggplot2::element_blank(),
      legend.position  = 'right',
      panel.border     = ggplot2::element_blank(),
      panel.grid.minor = ggplot2::element_blank(),
      panel.grid.major = ggplot2::element_line(colour = 'grey90', size = .25),
      legend.key       = ggplot2::element_rect(colour = NA, fill = NA),
      axis.line        = ggplot2::element_blank()
      )
}

library(ggplot2)


ggplot(temps_df, mapping=aes(x=fahr, y=celsius, color=kelvin)) +
    geom_point() +
    custom_theme(10)

```

